# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WebShow(object):
    def setupUi(self, WebShow):
        WebShow.setObjectName("WebShow")
        WebShow.resize(1000, 750)
        icon = QtGui.QIcon.fromTheme("D:\\share_ubuntu\\FreeCharts\\images\\logo.ico")
        WebShow.setWindowIcon(icon)
        self.frame_web = QtWidgets.QFrame(WebShow)
        self.frame_web.setGeometry(QtCore.QRect(0, 0, 700, 700))
        self.frame_web.setMinimumSize(QtCore.QSize(700, 700))
        self.frame_web.setMaximumSize(QtCore.QSize(700, 700))
        self.frame_web.setAutoFillBackground(False)
        self.frame_web.setStyleSheet("border:3px dashed #aaffff;")
        self.frame_web.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_web.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_web.setObjectName("frame_web")
        self.comboBox_ChartsStyles = QtWidgets.QComboBox(WebShow)
        self.comboBox_ChartsStyles.setGeometry(QtCore.QRect(800, 10, 121, 41))
        self.comboBox_ChartsStyles.setStyleSheet("border:3px solid #242424;")
        self.comboBox_ChartsStyles.setCurrentText("")
        self.comboBox_ChartsStyles.setObjectName("comboBox_ChartsStyles")
        self.lineEdit_X = QtWidgets.QLineEdit(WebShow)
        self.lineEdit_X.setGeometry(QtCore.QRect(720, 110, 271, 31))
        self.lineEdit_X.setAutoFillBackground(False)
        self.lineEdit_X.setStyleSheet("border:3px solid #000000;")
        self.lineEdit_X.setPlaceholderText("")
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.label = QtWidgets.QLabel(WebShow)
        self.label.setGeometry(QtCore.QRect(720, 71, 121, 31))
        self.label.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(WebShow)
        self.label_2.setGeometry(QtCore.QRect(720, 141, 111, 41))
        self.label_2.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_Y = QtWidgets.QLineEdit(WebShow)
        self.lineEdit_Y.setGeometry(QtCore.QRect(720, 180, 271, 31))
        self.lineEdit_Y.setStyleSheet("border:3px solid #000000;")
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.label_3 = QtWidgets.QLabel(WebShow)
        self.label_3.setGeometry(QtCore.QRect(720, 230, 111, 41))
        self.label_3.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_Title = QtWidgets.QLineEdit(WebShow)
        self.lineEdit_Title.setGeometry(QtCore.QRect(720, 270, 271, 31))
        self.lineEdit_Title.setStyleSheet("border:3px solid #000000;")
        self.lineEdit_Title.setObjectName("lineEdit_Title")
        self.label_4 = QtWidgets.QLabel(WebShow)
        self.label_4.setGeometry(QtCore.QRect(720, 300, 201, 31))
        self.label_4.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_DataName = QtWidgets.QLineEdit(WebShow)
        self.lineEdit_DataName.setGeometry(QtCore.QRect(720, 330, 271, 31))
        self.lineEdit_DataName.setStyleSheet("border:3px solid #000000;")
        self.lineEdit_DataName.setObjectName("lineEdit_DataName")
        self.pushButton_Generate = QtWidgets.QPushButton(WebShow)
        self.pushButton_Generate.setGeometry(QtCore.QRect(800, 430, 111, 51))
        self.pushButton_Generate.setStyleSheet("border:3px solid #000000;\n"
"font: 75 12pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_Generate.setObjectName("pushButton_Generate")
        self.checkBox_is_fitted = QtWidgets.QCheckBox(WebShow)
        self.checkBox_is_fitted.setGeometry(QtCore.QRect(720, 380, 271, 41))
        self.checkBox_is_fitted.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.checkBox_is_fitted.setObjectName("checkBox_is_fitted")

        self.retranslateUi(WebShow)
        QtCore.QMetaObject.connectSlotsByName(WebShow)

    def retranslateUi(self, WebShow):
        _translate = QtCore.QCoreApplication.translate
        WebShow.setWindowTitle(_translate("WebShow", "FreeCharts"))
        self.label.setText(_translate("WebShow", "X轴数据："))
        self.label_2.setText(_translate("WebShow", "Y轴数据："))
        self.label_3.setText(_translate("WebShow", "标题："))
        self.label_4.setText(_translate("WebShow", "数据名(选填)："))
        self.pushButton_Generate.setText(_translate("WebShow", "生成"))
        self.checkBox_is_fitted.setText(_translate("WebShow", "是否拟合直线"))
